services:
  mybank.web:
    image: ${DOCKER_REGISTRY-}mybankweb
    build:
      context: .
      dockerfile: MyBank.Web/Dockerfile
    environment:
      - ConnectionStrings__MyBankWebContextConnection=Server=db;Database=MyBank;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"